### ISSUE TITLE
expression '@' is returning array instead of current object

### ISSUE THREAD

**Issue by naivefun** [nanoporetech/jmespath-ts#3]
`search({}, "@")` is returning `[{}]`, expecting `{}` as on the official tutorials.

![image](https://user-images.githubusercontent.com/10683378/95591348-c5283800-0a79-11eb-9d0f-4ffbdd5d4d19.png)

**Comment by glenveegee** [comment]
I'm afraid I can't seem to reproduce the error you are seeing

<img width="894" alt="Screenshot 2020-10-09 at 16 01 05" src="https://user-images.githubusercontent.com/1570698/95599337-d9077600-0a48-11eb-95e3-ffbb7e7df246.png">

**Comment by naivefun** [comment]
You are right. My test case is:
```typescript
import {
  registerFunction,
  search,
  TYPE_OBJECT,
} from "@metrichor/jmespath-plus";

registerFunction(
  "toJSONString",
  (value) => {
    return JSON.stringify(value, null, 2);
  },
  [{ types: [TYPE_OBJECT] }]
);

console.log(":::", search({}, "toJSONString(@)"));
```

The toJSONString func is receiving `[{}]` as param, is it the expression syntax error?

**Comment by glenveegee** [comment]
So the third argument defines an array of input types (at least one) like this:
`[{ types: [TYPE_OBJECT] }]`

The custom function actually takes a validated args array so if you defined one input type, your `value` would be an array of one containing the resolved argument.

So the solution here is to destructure your args like this

```javascript
([value]) => {
    return JSON.stringify(value, null, 2);
},
```

**Comment by glenveegee** [comment]
FWIW: JSON.stringify can take any valid JSON type so your function could support 
```
[{ types: [TYPE_OBJECT, TYPE_ARRAY, TYPE_STRING, TYPE_BOOLEAN, TYPE_NULL, TYPE_NUMBER] }]
```

**Comment by glenveegee** [comment]
Thought you might like to know I've implemented fully typed `toJSON` and `fromJSON` jmespath builtins in our @metrichor/jmespath-plus (https://www.npmjs.com/package/@metrichor/jmespath-plus) package. This follows a change in this package (after looking into your issue) of providing optional arguments. 

Thanks again
