### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by beeing** [nanoporetech/jmespath-ts#8]
Hi, thanks for the rewrite and improvements.

One of the thing I find missing is the ability for replace.

`replace(data, 'expression', (value) => { return replacedvalue })`

This will open the library to more possibilities.

**Comment by glenveegee** [comment]
Hi @beeing. Thanks for the suggestion. Unfortunately this implementation sticks to the spec although we *have* deviated from the spec in one important way that will help you here - to allow users to register their own functions in the jmespath syntax. 

If you're looking for an out-of-the-box solution then we've already done this in our other library jmespath-plus (https://github.com/nanoporetech/jmespath-plus). In this library (spec compliant at its core) we've registered all available lodash functions so they can be used in jmespath expressions as well as a few extras. 

With `jmespath-plus` you can replace strings using the `_replace` function as follows:
```
locations[?state == 'WA'].[name, _replace(state, `W`, `Q`)]
```

If you would rather register your own function then it is already [documented in our readme](https://github.com/nanoporetech/jmespath-ts/blob/master/README.md#extensions-to-original-spec)
